// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using new_project_2.Data;

#nullable disable

namespace new_project_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("new_project_2.Models.Musteri", b =>
                {
                    b.Property<int>("idmusteriler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idmusteriler"));

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("musteriad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("musteriataadi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("musterisoyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idmusteriler");

                    b.ToTable("Musteriler");
                });
#pragma warning restore 612, 618
        }
    }
}
